### ISSUE TITLE
N4Pro and Octopi

### ISSUE THREAD

**Issue by michael2608H** [cvopicka/Kowalski-Configuration#1]
Hi, you seem to be an expert. I was running my former printer an Ender 3 with Octopi with a Pi3. Now switched to N4P and what a mess. I need to start ls /dev/serial/by-id/* on the printer to get the MCU, but it is not working. Any idea how to solve this ? Thank you.

**Comment by cvopicka** [comment]
Hello.  I don't know about an expert.  I just keep going til it works or breaks.  Yes, I was running Octopi on my Creality CR-6 SE.  Was fantastic! That is an amazing project.  I have since upgraded that to Klipper as well.  I just checked my N4Pro and found exactly what you suggest.  After logging into the printer with SSH the /dev/serial/by-id/* doesn't exist on the N4Pro in its current configuration.  This means you would need to know what /dev/tty* device it is.  In my case and all the printer.cfg's I have found it seems to be /dev/ttyS0

So my printer.cfg section looks like:

```
[mcu]
# The hardware use USART1 PA10/PA9 connect to RK3328
serial: /dev/ttyS0
restart_method: command
```

I guess there is no guarantee that this is yours as well so be cautious.  For the decades I have been using Linux I didn't even know the by-id existed until I started playing with Klipper, so I have always gone direct to the /dev/tty*.  

I do find it interesting that it is /dev/ttyS0 since my research earlier this month showed me that ttyS* was for true serial ports and I didn't think the MCU and CPU were connected directly over serial but over a USB Serial.  That was just my guess though.  I haven't taken my N4Pro apart to see yet.  

Does this help you?

**Comment by michael2608H** [comment]
Hi, thank you for your reply. Yes the TTYS0 I did also see. And I was also a bit curious to understand. When I type sudo systemctl list-units then you are seeing the whole configuration and TTYS0. So I will also investigate. But that bad made Klipper is quite annoying. THank you again. Lets stay in touch.
